apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: burrow
  labels:
    name: burrow
spec:
  selector:
    matchLabels:
      name: burrow
  template:
    metadata:
      labels:
        name: burrow
    spec:
      hostNetwork: true
      containers:
      - name: burrow
        image: jonathanbeber/burrow:0.1.0
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: BURROW_UPSTREAM_SERVER
          value: "1.1.1.1"
        ports:
        - name: tcp-dns
          containerPort: 53
          hostPort: 53
        - name: udp-dns
          containerPort: 53
          hostPort: 53
          protocol: UDP
